apiVersion: v1
kind: Namespace
metadata:
  name: otel-system
  labels:
    # app.kubernetes.io/name: standard label for identifying the application.
    app.kubernetes.io/name: otel-collector
    # app.kubernetes.io/part-of: groups all otel-starter resources for tooling like Helm and kubectl.
    app.kubernetes.io/part-of: otel-starter
